import type { SystemDef } from "./types.js";

/**
 * 主要システムのプリセット定義。
 *
 * 「そのまま遊べる出発点」であって公式データの完全再現ではない。
 * 各システム固有の複雑な処理(DX のクリティカル上方無限、エモクロアの
 * 成功数カウント等)はメモ(note)に明記し、ダイス結果から手で読み取る
 * 運用にしている。ビルダーで複製してから自由に調整できる。
 *
 * ライセンス方針(プリセットに含めてよいもの):
 *  - 能力値・技能の「名称」(短い語句 = 著作権保護の対象外)と、
 *    周知の基本判定式(ゲームルール = アイデアであり保護対象外)のみ。
 *  - 説明文(note / palette のコメント)はすべて自前の文章。
 *  - ルールブック本文・データ表・イラスト・ロゴは一切含めない。
 *  - 各 note に「ファンメイドの簡易テンプレート」であることを明示する。
 *  - D&D は SRD 5.1(CC-BY-4.0)の範囲に限定し、note に帰属表示を記載。
 */
export const SYSTEM_PRESETS: SystemDef[] = [
  {
    id: "preset-sw25",
    name: "ソード・ワールド2.5",
    icon: "⚔️",
    preset: true,
    diceBot: "sw25",
    checkTemplate: "2d6+{value}>=?",
    defaultRoll: "2d6",
    attributes: [
      { key: "DEX", label: "器用度B", initial: 4 },
      { key: "AGI", label: "敏捷度B", initial: 4 },
      { key: "STR", label: "筋力B", initial: 4 },
      { key: "VIT", label: "生命力B", initial: 4 },
      { key: "INT", label: "知力B", initial: 4 },
      { key: "MND", label: "精神力B", initial: 4 },
    ],
    skills: [
      { label: "冒険者レベル", initial: 1 },
      { label: "ファイター", initial: 0 },
      { label: "シューター", initial: 0 },
      { label: "ソーサラー", initial: 0 },
      { label: "プリースト", initial: 0 },
      { label: "スカウト", initial: 0 },
      { label: "セージ", initial: 0 },
    ],
    resources: [
      { key: "hp", label: "HP", max: 30 },
      { key: "mp", label: "MP", max: 20 },
    ],
    palette: [
      "# 判定（? を目標値に書き換え）",
      "2d6+{冒険者レベル}+{器用度B}>=? 命中判定",
      "2d6+{冒険者レベル}+{敏捷度B}>=? 回避判定",
      "2d6+{冒険者レベル}+{知力B}>=? 魔物知識",
      "2d6+{スカウト}+{敏捷度B}>=? 危険感知",
      "2d6 平目",
      "# ダメージ",
      "2d6 威力表は手で参照",
    ],
    note: "能力値ボーナス(B)を直接入力する簡易版。威力表・出目50のクリティカルは手動で参照してください。",
  },
  {
    id: "preset-dx3",
    name: "ダブルクロス The 3rd Edition",
    icon: "🧬",
    preset: true,
    diceBot: "dx3",
    checkTemplate: "{value}DX@10",
    defaultRoll: "1d10",
    attributes: [
      { key: "BODY", label: "肉体", initial: 2 },
      { key: "SENSE", label: "感覚", initial: 2 },
      { key: "MIND", label: "精神", initial: 2 },
      { key: "SOCIAL", label: "社会", initial: 2 },
    ],
    skills: [
      { label: "白兵", initial: 0 },
      { label: "射撃", initial: 0 },
      { label: "知覚", initial: 0 },
      { label: "RC", initial: 0 },
      { label: "意志", initial: 0 },
      { label: "交渉", initial: 0 },
    ],
    resources: [
      { key: "hp", label: "HP", max: 25 },
      { key: "erosion", label: "侵蝕率", max: 150 },
      { key: "lois", label: "ロイス", max: 7 },
    ],
    palette: [
      "# 判定（XDX@クリティカル値。振り足し・達成値は自動計算）",
      "{肉体}DX@10 肉体判定",
      "{感覚}DX@10 感覚判定",
      "{精神}DX@10 精神判定",
      "{社会}DX@10 社会判定",
      "1d10 侵蝕ダイス",
      "# 登場時 1d10 を侵蝕率に加算",
    ],
    note: "ダイスボット「ダブルクロス The 3rd」で XDX@C+m>=t が使えます(クリティカル振り足しと達成値を自動計算)。侵蝕率は + で増やします。",
  },
  {
    id: "preset-shinobigami",
    name: "シノビガミ",
    icon: "🥷",
    preset: true,
    diceBot: "shinobigami",
    checkTemplate: "2d6>=5",
    defaultRoll: "2d6",
    attributes: [],
    skills: [
      { label: "器術", initial: 0 },
      { label: "体術", initial: 0 },
      { label: "忍術", initial: 0 },
      { label: "謀術", initial: 0 },
      { label: "戦術", initial: 0 },
      { label: "妖術", initial: 0 },
    ],
    resources: [
      { key: "hp", label: "生命力", max: 6 },
      { key: "cred", label: "功績点", max: 10 },
    ],
    palette: [
      "# 判定（指定特技からの目標値を >= の後に。基本 5、1 離れるごと +1）",
      "2d6>=5 判定",
      "2d6>=7 判定（2 つ離れた特技）",
      "1d6 ダメージ/感情表など",
      "2d6 ファンブル表",
    ],
    note: "特技リスト(6分野×11)はメモ欄に記入してください。スペシャル(12)/ファンブル(2)は出目で確認します。",
  },
  {
    id: "preset-paranoia",
    name: "パラノイア",
    icon: "🤖",
    preset: true,
    diceBot: "paranoia",
    checkTemplate: "1d20<={value}",
    defaultRoll: "1d20",
    attributes: [
      { key: "VIO", label: "暴力", initial: 8 },
      { key: "BRA", label: "頭脳", initial: 8 },
      { key: "CHU", label: "口先", initial: 8 },
      { key: "MEC", label: "機械", initial: 8 },
    ],
    skills: [
      { label: "エネルギー兵器", initial: 8 },
      { label: "尋問", initial: 8 },
      { label: "コンピュータ", initial: 8 },
    ],
    resources: [
      { key: "clone", label: "クローン残機", max: 6 },
      { key: "moxie", label: "モクシー", max: 8 },
    ],
    palette: [
      "# 判定（1d20 が技能値以下で成功）",
      "1d20<={暴力} 暴力判定",
      "1d20<={頭脳} 頭脳判定",
      "1d20<={口先} 口先判定",
      "1d20<={機械} 機械判定",
      "# 幸福は義務です。コンピュータ様は あなたの友達です",
    ],
    note: "版によって判定方式が異なります(これは d20 ロールアンダーの簡易版)。機密情報の閲覧は反逆です。",
  },
  {
    id: "preset-tnova",
    name: "トーキョーN◎VA",
    icon: "🃏",
    preset: true,
    checkTemplate: "1d13+{value}",
    defaultRoll: "1d13",
    attributes: [
      { key: "REASON", label: "理性", initial: 5 },
      { key: "PASSION", label: "感情", initial: 5 },
      { key: "LIFE", label: "生命", initial: 5 },
      { key: "OUTER", label: "外界", initial: 5 },
    ],
    skills: [
      { label: "〈白兵〉", initial: 0 },
      { label: "〈射撃〉", initial: 0 },
      { label: "〈交渉〉", initial: 0 },
      { label: "〈操縦〉", initial: 0 },
    ],
    resources: [{ key: "kamiwaza", label: "神業", max: 3 }],
    palette: [
      "# 本来は神業カード(トランプ)制。1d13 で代用(1=A … 13=K)",
      "1d13+{理性} 理性判定",
      "1d13+{感情} 感情判定",
      "1d13+{生命} 生命判定",
      "1d13+{外界} 外界判定",
    ],
    note: "カード(トランプ)制を 1d13 で代用した簡易版です。スートと切り札(神業)は口頭/メモで管理してください。",
  },
  {
    id: "preset-yuyake",
    name: "ゆうやけこやけ",
    icon: "🦊",
    preset: true,
    defaultRoll: "1d6",
    attributes: [
      { key: "HENGE", label: "へんげ", initial: 2 },
      { key: "MONONOKE", label: "もののけ", initial: 1 },
      { key: "OTONA", label: "おとな", initial: 1 },
      { key: "KODOMO", label: "こども", initial: 2 },
    ],
    skills: [],
    resources: [
      { key: "fushigi", label: "不思議", max: 8 },
      { key: "omoi", label: "想い", max: 8 },
      { key: "yume", label: "夢", max: 10 },
    ],
    palette: [
      "# 判定はダイスではなく【不思議】【想い】の消費宣言で行います",
      "「不思議を 1 つかいます」",
      "「想いを 1 つかいます」",
      "1d6 こまったときのおまかせダイス",
    ],
    note: "対決や乱数のないやさしいシステムです。特技や変化(へんげ)の内容はメモ欄へ。",
  },
  {
    id: "preset-nechronica",
    name: "永い後日談のネクロニカ",
    icon: "🪆",
    preset: true,
    diceBot: "nechronica",
    checkTemplate: "NC+{value}",
    defaultRoll: "1d10",
    attributes: [],
    skills: [
      { label: "運動", initial: 0 },
      { label: "知覚", initial: 0 },
      { label: "交渉", initial: 0 },
      { label: "工作", initial: 0 },
    ],
    resources: [
      { key: "head", label: "部位:頭", max: 2 },
      { key: "arm", label: "部位:腕", max: 2 },
      { key: "body", label: "部位:胴", max: 3 },
      { key: "leg", label: "部位:脚", max: 2 },
      { key: "ap", label: "行動値", max: 12 },
      { key: "favor", label: "寵愛", max: 10 },
    ],
    palette: [
      "# 行為判定: NC+補正（6以上=成功 / 11以上=大成功 / 出目1=ファンブル）",
      "NC 行為判定",
      "NC+1 行為判定（強化パーツ +1）",
      "1d10 狂気点チェック",
    ],
    note: "パーツ(部位)の損傷はリソースの - で管理してください。マニューバはメモ欄かチャットパレットに追記を。",
  },
  {
    id: "preset-insane",
    name: "インセイン",
    icon: "🧠",
    preset: true,
    diceBot: "sf",
    checkTemplate: "2d6>=5",
    defaultRoll: "2d6",
    attributes: [],
    skills: [
      { label: "暴力", initial: 0 },
      { label: "情動", initial: 0 },
      { label: "知覚", initial: 0 },
      { label: "技術", initial: 0 },
      { label: "知識", initial: 0 },
      { label: "怪異", initial: 0 },
    ],
    resources: [
      { key: "hp", label: "生命力", max: 6 },
      { key: "san", label: "正気度", max: 6 },
    ],
    palette: [
      "# 判定（指定特技からの目標値を >= の後に。基本 5、1 離れるごと +1）",
      "2d6>=5 判定",
      "2d6>=7 判定（2 つ離れた特技）",
      "2d6 恐怖判定",
      "1d6 各種表",
    ],
    note: "特技リスト(6分野×11)・狂気カード・ハンドアウトはメモ欄に記入してください。正気度の減少はリソースの - で。ファンメイドの簡易テンプレートです。",
  },
  {
    id: "preset-magicalogia",
    name: "マギカロギア",
    icon: "📖",
    preset: true,
    diceBot: "sf",
    checkTemplate: "2d6>=5",
    defaultRoll: "2d6",
    attributes: [],
    skills: [
      { label: "星", initial: 0 },
      { label: "獣", initial: 0 },
      { label: "力", initial: 0 },
      { label: "歌", initial: 0 },
      { label: "夢", initial: 0 },
      { label: "闇", initial: 0 },
    ],
    resources: [
      { key: "root", label: "根源力", max: 6 },
      { key: "mana", label: "魔力", max: 10 },
    ],
    palette: [
      "# 判定（指定特技からの目標値を >= の後に。基本 5、1 離れるごと +1）",
      "2d6>=5 判定",
      "2d6>=7 判定（2 つ離れた特技）",
      "1d6 各種表",
    ],
    note: "特技リスト(6分野×11)・魔法(蔵書)・アンカーはメモ欄へ。プロットや魔素の詳細処理は手動で行ってください。ファンメイドの簡易テンプレートです。",
  },
  {
    id: "preset-arianrhod2e",
    name: "アリアンロッド2E",
    icon: "🛡️",
    preset: true,
    checkTemplate: "2d6+{value}>=?",
    defaultRoll: "2d6",
    attributes: [
      { key: "STR", label: "筋力B", initial: 2 },
      { key: "DEX", label: "器用B", initial: 2 },
      { key: "AGI", label: "敏捷B", initial: 2 },
      { key: "INT", label: "知力B", initial: 2 },
      { key: "SEN", label: "感知B", initial: 2 },
      { key: "MND", label: "精神B", initial: 2 },
      { key: "LUK", label: "幸運B", initial: 2 },
    ],
    skills: [{ label: "キャラクターレベル", initial: 1 }],
    resources: [
      { key: "hp", label: "HP", max: 30 },
      { key: "mp", label: "MP", max: 20 },
      { key: "fate", label: "フェイト", max: 5 },
    ],
    palette: [
      "# 判定（2D+能力ボーナス。? を目標値に書き換え）",
      "2d6+{筋力B}>=? 筋力判定",
      "2d6+{器用B}>=? 器用判定",
      "2d6+{敏捷B}>=? 敏捷判定",
      "2d6+{知力B}>=? 知力判定",
      "2d6+{感知B}>=? 感知判定",
      "2d6 命中・回避はスキル値を足して",
    ],
    note: "能力ボーナス(基本値)を直接入力する簡易版です。クリティカル(6ゾロ)・ファンブル(1ゾロ)の処理とスキル・ギルドはメモ欄で管理してください。ファンメイドの簡易テンプレートです。",
  },
  {
    id: "preset-loghorizon",
    name: "ログ・ホライズンTRPG",
    icon: "🏰",
    preset: true,
    checkTemplate: "2d6+{value}>=?",
    defaultRoll: "2d6",
    attributes: [
      { key: "STR", label: "STR基本値", initial: 2 },
      { key: "DEX", label: "DEX基本値", initial: 2 },
      { key: "POW", label: "POW基本値", initial: 2 },
      { key: "INT", label: "INT基本値", initial: 2 },
    ],
    skills: [
      { label: "運動", initial: 2 },
      { label: "耐久", initial: 2 },
      { label: "解除", initial: 2 },
      { label: "操作", initial: 2 },
      { label: "知覚", initial: 2 },
      { label: "交渉", initial: 2 },
      { label: "知識", initial: 2 },
      { label: "幸運", initial: 2 },
    ],
    resources: [
      { key: "hp", label: "HP", max: 40 },
      { key: "fate", label: "因果力", max: 5 },
    ],
    palette: [
      "# 判定（2D+技能基本値。? を目標値/対決値に書き換え）",
      "2d6+{運動}>=? 運動判定",
      "2d6+{知覚}>=? 知覚判定",
      "2d6+{交渉}>=? 交渉判定",
      "2d6+{知識}>=? 知識判定",
      "2d6 ダメージロールは特技参照",
    ],
    note: "ルールブックは公式サイトで無料公開されています。特技・アイテム・ヘイト管理はメモ欄へ。ファンメイドの簡易テンプレートです。",
  },
  {
    id: "preset-dnd5e",
    name: "D&D 第5版 (SRD)",
    icon: "🐉",
    preset: true,
    diceBot: "d20",
    checkTemplate: "1d20+{value}>=?",
    defaultRoll: "1d20",
    attributes: [
      { key: "STR", label: "筋力修正", initial: 0 },
      { key: "DEX", label: "敏捷修正", initial: 0 },
      { key: "CON", label: "耐久修正", initial: 0 },
      { key: "INT", label: "知力修正", initial: 0 },
      { key: "WIS", label: "判断修正", initial: 0 },
      { key: "CHA", label: "魅力修正", initial: 0 },
    ],
    skills: [
      { label: "習熟ボーナス", initial: 2 },
      { label: "運動", initial: 0 },
      { label: "隠密", initial: 0 },
      { label: "知覚", initial: 0 },
      { label: "捜査", initial: 0 },
      { label: "説得", initial: 0 },
      { label: "魔法学", initial: 0 },
    ],
    resources: [
      { key: "hp", label: "HP", max: 10 },
      { key: "insp", label: "インスピレーション", max: 1 },
    ],
    palette: [
      "# 判定: 1d20+修正（有利/不利は 2d20 を振って高い/低い方を採用）",
      "1d20+{筋力修正}>=? 筋力判定",
      "1d20+{敏捷修正}>=? 敏捷判定",
      "1d20+{判断修正}>=? 判断判定",
      "2d20 有利・不利用",
      "1d20 イニシアチブは敏捷修正を足して",
    ],
    note: "能力値スコアではなく修正値を直接入力する簡易版です(技能は合計修正を入力)。This work includes material from the System Reference Document 5.1 by Wizards of the Coast LLC, available under CC-BY-4.0. ファンメイドの簡易テンプレートです。",
  },
  {
    id: "preset-emoklore",
    name: "エモクロアTRPG",
    icon: "👁",
    preset: true,
    diceBot: "emoklore",
    checkTemplate: "{value}DM<=?",
    defaultRoll: "1d10",
    attributes: [
      { key: "BODY", label: "身体", initial: 2 },
      { key: "DEX", label: "器用", initial: 2 },
      { key: "MIND", label: "精神", initial: 2 },
      { key: "SENSE", label: "五感", initial: 2 },
      { key: "INT", label: "知力", initial: 2 },
      { key: "CHARM", label: "魅力", initial: 2 },
      { key: "SOCIAL", label: "社会", initial: 2 },
      { key: "LUCK", label: "運勢", initial: 2 },
    ],
    skills: [
      { label: "観察眼", initial: 1 },
      { label: "聞き耳", initial: 1 },
      { label: "調査", initial: 1 },
      { label: "心理", initial: 1 },
    ],
    resources: [
      { key: "hp", label: "HP", max: 10 },
      { key: "mp", label: "MP", max: 10 },
      { key: "resonance", label: "共鳴", max: 10 },
    ],
    palette: [
      "# 判定: 技能LvDM<=能力値（成功数を自動カウント。1=ダブル / 10=ファンブル）",
      "{観察眼}DM<={五感} 観察眼",
      "{聞き耳}DM<={五感} 聞き耳",
      "{調査}DM<={知力} 調査",
      "{心理}DM<={精神} 心理",
      "1d10 ダイス 1 個",
    ],
    note: "ダイスボット「エモクロアTRPG」で XDM<=能力値 の成功数カウントが自動です(1=ダブル / 10=ファンブル)。共鳴値は + で上げます。",
  },
];
