import type { SystemDef } from "./types.js";

/**
 * 主要システムのプリセット定義。
 *
 * 「そのまま遊べる出発点」であって公式データの完全再現ではない。
 * 各システム固有の複雑な処理(DX のクリティカル上方無限、エモクロアの
 * 成功数カウント等)はメモ(note)に明記し、ダイス結果から手で読み取る
 * 運用にしている。ビルダーで複製してから自由に調整できる。
 */
export const SYSTEM_PRESETS: SystemDef[] = [
  {
    id: "preset-sw25",
    name: "ソード・ワールド2.5",
    icon: "⚔️",
    preset: true,
    checkTemplate: "2d6+{value}>=?",
    defaultRoll: "2d6",
    attributes: [
      { key: "DEX", label: "器用度B", initial: 4 },
      { key: "AGI", label: "敏捷度B", initial: 4 },
      { key: "STR", label: "筋力B", initial: 4 },
      { key: "VIT", label: "生命力B", initial: 4 },
      { key: "INT", label: "知力B", initial: 4 },
      { key: "MND", label: "精神力B", initial: 4 },
    ],
    skills: [
      { label: "冒険者レベル", initial: 1 },
      { label: "ファイター", initial: 0 },
      { label: "シューター", initial: 0 },
      { label: "ソーサラー", initial: 0 },
      { label: "プリースト", initial: 0 },
      { label: "スカウト", initial: 0 },
      { label: "セージ", initial: 0 },
    ],
    resources: [
      { key: "hp", label: "HP", max: 30 },
      { key: "mp", label: "MP", max: 20 },
    ],
    palette: [
      "# 判定（? を目標値に書き換え）",
      "2d6+{冒険者レベル}+{器用度B}>=? 命中判定",
      "2d6+{冒険者レベル}+{敏捷度B}>=? 回避判定",
      "2d6+{冒険者レベル}+{知力B}>=? 魔物知識",
      "2d6+{スカウト}+{敏捷度B}>=? 危険感知",
      "2d6 平目",
      "# ダメージ",
      "2d6 威力表は手で参照",
    ],
    note: "能力値ボーナス(B)を直接入力する簡易版。威力表・出目50のクリティカルは手動で参照してください。",
  },
  {
    id: "preset-dx3",
    name: "ダブルクロス The 3rd Edition",
    icon: "🧬",
    preset: true,
    checkTemplate: "{value}d10",
    defaultRoll: "1d10",
    attributes: [
      { key: "BODY", label: "肉体", initial: 2 },
      { key: "SENSE", label: "感覚", initial: 2 },
      { key: "MIND", label: "精神", initial: 2 },
      { key: "SOCIAL", label: "社会", initial: 2 },
    ],
    skills: [
      { label: "白兵", initial: 0 },
      { label: "射撃", initial: 0 },
      { label: "知覚", initial: 0 },
      { label: "RC", initial: 0 },
      { label: "意志", initial: 0 },
      { label: "交渉", initial: 0 },
    ],
    resources: [
      { key: "hp", label: "HP", max: 25 },
      { key: "erosion", label: "侵蝕率", max: 150 },
      { key: "lois", label: "ロイス", max: 7 },
    ],
    palette: [
      "# 判定（能力値の個数だけ d10。10 はクリティカルで振り足し=手動）",
      "{肉体}d10 肉体判定",
      "{感覚}d10 感覚判定",
      "{精神}d10 精神判定",
      "{社会}d10 社会判定",
      "1d10 侵蝕ダイス",
      "# 登場時 1d10 を侵蝕率に加算",
    ],
    note: "クリティカル(出目10の振り足し)と達成値計算は出目から手動で処理してください。侵蝕率は + で増やします。",
  },
  {
    id: "preset-shinobigami",
    name: "シノビガミ",
    icon: "🥷",
    preset: true,
    checkTemplate: "2d6>=5",
    defaultRoll: "2d6",
    attributes: [],
    skills: [
      { label: "器術", initial: 0 },
      { label: "体術", initial: 0 },
      { label: "忍術", initial: 0 },
      { label: "謀術", initial: 0 },
      { label: "戦術", initial: 0 },
      { label: "妖術", initial: 0 },
    ],
    resources: [
      { key: "hp", label: "生命力", max: 6 },
      { key: "cred", label: "功績点", max: 10 },
    ],
    palette: [
      "# 判定（指定特技からの目標値を >= の後に。基本 5、1 離れるごと +1）",
      "2d6>=5 判定",
      "2d6>=7 判定（2 つ離れた特技）",
      "1d6 ダメージ/感情表など",
      "2d6 ファンブル表",
    ],
    note: "特技リスト(6分野×11)はメモ欄に記入してください。スペシャル(12)/ファンブル(2)は出目で確認します。",
  },
  {
    id: "preset-paranoia",
    name: "パラノイア",
    icon: "🤖",
    preset: true,
    checkTemplate: "1d20<={value}",
    defaultRoll: "1d20",
    attributes: [
      { key: "VIO", label: "暴力", initial: 8 },
      { key: "BRA", label: "頭脳", initial: 8 },
      { key: "CHU", label: "口先", initial: 8 },
      { key: "MEC", label: "機械", initial: 8 },
    ],
    skills: [
      { label: "エネルギー兵器", initial: 8 },
      { label: "尋問", initial: 8 },
      { label: "コンピュータ", initial: 8 },
    ],
    resources: [
      { key: "clone", label: "クローン残機", max: 6 },
      { key: "moxie", label: "モクシー", max: 8 },
    ],
    palette: [
      "# 判定（1d20 が技能値以下で成功）",
      "1d20<={暴力} 暴力判定",
      "1d20<={頭脳} 頭脳判定",
      "1d20<={口先} 口先判定",
      "1d20<={機械} 機械判定",
      "# 幸福は義務です。コンピュータ様は あなたの友達です",
    ],
    note: "版によって判定方式が異なります(これは d20 ロールアンダーの簡易版)。機密情報の閲覧は反逆です。",
  },
  {
    id: "preset-tnova",
    name: "トーキョーN◎VA",
    icon: "🃏",
    preset: true,
    checkTemplate: "1d13+{value}",
    defaultRoll: "1d13",
    attributes: [
      { key: "REASON", label: "理性", initial: 5 },
      { key: "PASSION", label: "感情", initial: 5 },
      { key: "LIFE", label: "生命", initial: 5 },
      { key: "OUTER", label: "外界", initial: 5 },
    ],
    skills: [
      { label: "〈白兵〉", initial: 0 },
      { label: "〈射撃〉", initial: 0 },
      { label: "〈交渉〉", initial: 0 },
      { label: "〈操縦〉", initial: 0 },
    ],
    resources: [{ key: "kamiwaza", label: "神業", max: 3 }],
    palette: [
      "# 本来は神業カード(トランプ)制。1d13 で代用(1=A … 13=K)",
      "1d13+{理性} 理性判定",
      "1d13+{感情} 感情判定",
      "1d13+{生命} 生命判定",
      "1d13+{外界} 外界判定",
    ],
    note: "カード(トランプ)制を 1d13 で代用した簡易版です。スートと切り札(神業)は口頭/メモで管理してください。",
  },
  {
    id: "preset-yuyake",
    name: "ゆうやけこやけ",
    icon: "🦊",
    preset: true,
    defaultRoll: "1d6",
    attributes: [
      { key: "HENGE", label: "へんげ", initial: 2 },
      { key: "MONONOKE", label: "もののけ", initial: 1 },
      { key: "OTONA", label: "おとな", initial: 1 },
      { key: "KODOMO", label: "こども", initial: 2 },
    ],
    skills: [],
    resources: [
      { key: "fushigi", label: "不思議", max: 8 },
      { key: "omoi", label: "想い", max: 8 },
      { key: "yume", label: "夢", max: 10 },
    ],
    palette: [
      "# 判定はダイスではなく【不思議】【想い】の消費宣言で行います",
      "「不思議を 1 つかいます」",
      "「想いを 1 つかいます」",
      "1d6 こまったときのおまかせダイス",
    ],
    note: "対決や乱数のないやさしいシステムです。特技や変化(へんげ)の内容はメモ欄へ。",
  },
  {
    id: "preset-nechronica",
    name: "永い後日談のネクロニカ",
    icon: "🪆",
    preset: true,
    checkTemplate: "1d10>=6",
    defaultRoll: "1d10",
    attributes: [],
    skills: [
      { label: "運動", initial: 0 },
      { label: "知覚", initial: 0 },
      { label: "交渉", initial: 0 },
      { label: "工作", initial: 0 },
    ],
    resources: [
      { key: "head", label: "部位:頭", max: 2 },
      { key: "arm", label: "部位:腕", max: 2 },
      { key: "body", label: "部位:胴", max: 3 },
      { key: "leg", label: "部位:脚", max: 2 },
      { key: "ap", label: "行動値", max: 12 },
      { key: "favor", label: "寵愛", max: 10 },
    ],
    palette: [
      "# 行為判定: 1d10 ≥ 6 成功（10 は大成功）。補正は +N で",
      "1d10>=6 行為判定",
      "1d10+1>=6 行為判定（強化パーツ +1）",
      "1d10 狂気点チェック",
    ],
    note: "パーツ(部位)の損傷はリソースの - で管理してください。マニューバはメモ欄かチャットパレットに追記を。",
  },
  {
    id: "preset-emoklore",
    name: "エモクロアTRPG",
    icon: "👁",
    preset: true,
    checkTemplate: "{value}d10",
    defaultRoll: "1d10",
    attributes: [
      { key: "BODY", label: "身体", initial: 2 },
      { key: "DEX", label: "器用", initial: 2 },
      { key: "MIND", label: "精神", initial: 2 },
      { key: "SENSE", label: "五感", initial: 2 },
      { key: "INT", label: "知力", initial: 2 },
      { key: "CHARM", label: "魅力", initial: 2 },
      { key: "SOCIAL", label: "社会", initial: 2 },
      { key: "LUCK", label: "運勢", initial: 2 },
    ],
    skills: [
      { label: "観察眼", initial: 1 },
      { label: "聞き耳", initial: 1 },
      { label: "調査", initial: 1 },
      { label: "心理", initial: 1 },
    ],
    resources: [
      { key: "hp", label: "HP", max: 10 },
      { key: "mp", label: "MP", max: 10 },
      { key: "resonance", label: "共鳴", max: 10 },
    ],
    palette: [
      "# 技能レベル個数の d10 を振り、対応能力値以下の出目 1 つごとに成功",
      "{観察眼}d10 観察眼（五感 {五感} 以下が成功）",
      "{調査}d10 調査（知力 {知力} 以下が成功）",
      "1d10 ダイス 1 個",
    ],
    note: "成功数(能力値以下の出目の個数)は出目から手で数えてください。共鳴値は + で上げます。",
  },
];
